name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (for Tailwind CSS)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g tailwindcss
          npm install

      - name: Build TailwindCSS
        run: |
          npx tailwindcss build src/styles.css -o dist/styles.css

      - name: Deploy (optional, add your deployment steps here)
        run: |
          echo "Add your deployment steps here"
